# Getting Started with NumPy
Course: https://app.pluralsight.com/library/courses/numpy-getting-started

In [3]:
import numpy as np

In [7]:
# Create One Dimensional Array
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [53]:
# 2 dimensional array
two_dim_arr = np.array(([1, 2], [3, 4], [5, "HELLO"]))
print(two_dim_arr)

[['1' '2']
 ['3' '4']
 ['5' 'HELLO']]


In [56]:
two_dim_arr.dtype

dtype('<U21')

## NDarray attributes

In [63]:
# Shape gives you the shape of the array size and dimension
two_dim_arr.shape

(3, 2)

In [64]:
# Get the dimension
two_dim_arr.ndim

2

In [65]:
# Get the size
two_dim_arr.size

6

## Creating arrays

In [105]:
empty_arr = np.empty(shape=(1, 2), dtype=int)
print(empty_arr)  # Contains random values

[[2452371359472             0]]


In [110]:
full_array = np.full(shape=(2, 2), fill_value=10, dtype=int)
print(full_array) # Is filled with 10

[[10 10]
 [10 10]]


In [111]:
zero_arr = np.zeros(shape=(2,2))
print(zero_arr)

[[0. 0.]
 [0. 0.]]
